---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service
      command: service nginx status
    
    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 service
      command: service apache2 status

    - name: verify apache is listening on 80
      wait_for: port=80 timeout=1


- hosts: database
  become: true
  tasks:
    - name: verify mysql service
      command: service mysql status

    - name: verify mysql is listening on 3306
      wait_for: port=3306 timeout=1

- hosts: control
  tasks:
    - name: verify end to end response
      uri: url=http://lb01:8001 return_content=yes
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in lb_index.content"
    
    - name: verify end to end db response
      uri: url=http://lb01:8001/db return_content=yes
      register: lb_db
    
    - fail: msg="db failed to return content"
      when: "'Database Connected from' not in lb_db.content"

- hosts: loadbalancer
  tasks:
    - name: verify backend index response
      uri: url=http://{{item}} return_content=yes
      with_items: 
        - app01
        - app02
      register: app_index
    
    - fail: msg="index failed to return content"
      when: "'Hello, from sunny {{item.item}}!' not in item.content"
      with_items: "{{app_index.results}}"
    
    - name: verify backend db index response
      uri: url=http://{{item}}/db return_content=yes
      with_items:
        - app01
        - app02
      register: app_db
    
    - fail: msg="db failed to return content"
      when: "'Database Connected from {{item.item}}!' not in item.content"
      with_items: "{{app_db.results}}"
    

      